### ISSUE TITLE
IN : saisie réalisation

### ISSUE THREAD

**Issue by joelclems** [PnCevennes/app_oeasc#15]
Evaluer et finaliser/tester la saisie des réalisation des circuits des indices nocturnes.

**Comment by BaptisteAlgoet** [comment]
Penser à ajouter le nombre de groupes (champ à rendre facultatif, car pas toujours renseigné correctement sur les fiches), pour l'espèce Cerf.

**Comment by joelclems** [comment]
TODO

- [ ] store utils: fonction génériquepour créer un store (créer une issue ?)
  - [x] state, mutation, getters, actions
  - [ ] tester
  - [ ] ajout route auto en python !!!!
  
- [ ] corriger bug modifier
- [ ] affichage realisation
  - [ ] normal
  - [ ] tableau
- [ ] corriger bug liste
- [ ] ajouter nb groupe
- [ ] valide sur realisation et non observation
