### ISSUE TITLE
IN : gestion des circuits

### ISSUE THREAD

**Issue by joelclems** [PnCevennes/app_oeasc#16]
Créer une page d'édition / ajout de circuits.
- ajouter un champs `actif` pour les circuits
- pouvoir gérer quand les circuits change légèrement (ajouter un intervalle de temps au nom de l'ancien circuit??)
- possiblité de choisir tout les circuits ou que les circuits actifs dans le formulaire des réalisations (cf #15)

**Comment by BaptisteAlgoet** [comment]
Précisions sur le mode de fonctionnement, quand on modifie (même légèrement) un circuit :
- On renomme le circuit à modifier "NOM_20XX-20YY" (année début - année fin)
- On le désactive (pour la saisie, par pour l'analyse)
- On crée un nouveau circuit (actif)
- On le nomme avec le bon nom (d'usage, "propre") de circuit

**Comment by joelclems** [comment]
On peut gerer les circuit dans la partie admin des IN,... pas évident à désactiver pour la saisie

**Comment by BaptisteAlgoet** [comment]
- [ ] Reste juste à ajouter 1 case actif / inactif pour chaque circuit
