### ISSUE TITLE
BD user : modif adresses mail

### ISSUE THREAD

**Issue by BaptisteAlgoet** [PnCevennes/app_oeasc#21]
Dans les e-mails, remplacer @irstea.fr par @inrae.fr
Modif. indiquée comme faite dans le pad, mais elle ne semble pas effective.
Je suppose que c'est parce que adresse mail = identifiant, et que c'est compliqué à changer ?
A voir comment c'est gérable : soit on modifie nous-mêmes leur identifiant et on les prévient qu'on a mis à jour nous-mêmes leur id et adresse mail, soit on leur demande de modifier eux-mêmes leur adresse mail depuis leur compte utilisateur (mais après vérification, ça n'a pas l'air possible : e-mail et organisme apparaissent en grisé si je clique sur "modifier" dans mon espace utilisateur)

**Comment by joelclems** [comment]
Il vaut mieux les changer manuellement et les prévenir
