### ISSUE TITLE
IN : restitution

### ISSUE THREAD

**Issue by BaptisteAlgoet** [PnCevennes/app_oeasc#24]
Prévoir 2 niveaux de restitution : 1 page "admin" + 1 page "grand public"

Page "grand public" : 
- 1 cadre de texte (modifiable) en intro
- 1 graphique par secteur et par espèce (à dérouler - en accordéon), suivi d'un petit texte de commentaire
- Sur chaque graphique, affichage des points (non reliés entre eux) et des intervalles de confiance
- Tracé de la droite de régression selon la p-value (train plein si p-value < 0,05 ; pointillés si 0,05 < p-value < 0,10 ; non visible si p-value > 0,10)

Page "admin" : 
 - graphiques interactifs
 - résultats de la régression linéaire (équation de la droite de régression + p-value)
 - tableaux de validation / invalidation des circuits
 
A prévoir, en +, sur la page "admin" : 
- [ ] un tableau présentant, pour chaque circuit, le nombre de circuits et de répétition par année
- [ ] une fonctionnalité "export en JPG" des graphiques

Remarques : 
  - Attention au cas particulier du Causse, à traiter comme 2 massifs : "Causse - coeur" et "Ensemble du Causse"
  - Dans les graphiques, voir s'il est possible de réduire la taille des traits horizontaux marquant les intervalles de confiance. Si non, au pire, supprimer carrément ces traits horizontaux pour ne garder que les traits verticaux.

**Comment by joelclems** [comment]
*pour suivi*

Prévoir 2 niveaux de restitution : 1 page "admin" + 1 page "grand public"

Page "grand public" : 
- 1 cadre de texte (modifiable) en intro
- 1 graphique par secteur et par espèce (à dérouler - en accordéon), suivi d'un petit texte de commentaire
- Sur chaque graphique, affichage des points (non reliés entre eux) et des intervalles de confiance
- Tracé de la droite de régression selon la p-value (train plein si p-value < 0,05 ; pointillés si 0,05 < p-value < 0,10 ; non visible si p-value > 0,10)

Page "admin" : 
 - graphiques interactifs
 - résultats de la régression linéaire (équation de la droite de régression + p-value)
 - tableaux de validation / invalidation des circuits
 
A prévoir, en +, sur la page "admin" : 
- [ ] un tableau présentant, pour chaque circuit, le nombre de circuits et de répétition par année
- [ ] une fonctionnalité "export en JPG" des graphiques

Remarques : 
  - Attention au cas particulier du Causse, à traiter comme 2 massifs : "Causse - coeur" et "Ensemble du Causse"
  - ~~Dans les graphiques, voir s'il est possible de réduire la taille des traits horizontaux marquant les intervalles de confiance. Si non, au pire, supprimer carrément ces traits horizontaux pour ne garder que les traits verticaux.~~

**Comment by BaptisteAlgoet** [comment]
Quand tu barres, est-ce que ça veut dire que c'est fait, ou qu'il n'est pas possible de le faire ?

**Comment by joelclems** [comment]
C'est que c'est fait (mais tu verras pas le résultat tout de suite)

**Comment by joelclems** [comment]
pour la partie grand public, je peux faire en sorte que tu puisse mettre des graph dans le texte (avec accordéon ça doit être possible aussi. Les commentaires ce serait un commentaire pour tous les graph?

**Comment by BaptisteAlgoet** [comment]
Je suis pas sûr de comprendre, mais le mieux serait que tu prévois toi-même les graphes issus directement et mis en forme automatiquement de l'analyse (pour que je n'ai pas besoin de les exporter), avec juste un commentaire texte éditable par graphe...

Ça répond à ta question ou j'ai mal compris ?

**Comment by joelclems** [comment]
tu peux regarder sur https://oeasc.cevennes-parcnational.net/front/#/in/resultats
il y a des exemples de commentaires pour les Cerfs.
J'essaierai de faire en sorte que les commentaires soient mieux intégrés au graphs

**Comment by BaptisteAlgoet** [comment]
J'ai fait un test.
Si je rentre un texte court, ça fonctionne bien.
![image](https://user-images.githubusercontent.com/68336175/89265902-7e5f3180-d635-11ea-9a8e-0dad47d78d95.png)

Par contre, si je rentre un texte plus long, ...
![image](https://user-images.githubusercontent.com/68336175/89266048-b797a180-d635-11ea-992f-2826e0495740.png)

... la page devient blanche.
![image](https://user-images.githubusercontent.com/68336175/89266080-c2523680-d635-11ea-835b-7156dc760099.png)

**Comment by joelclems** [comment]
Il faut mettre `\'` pour les apastrophes. (`l'\'interpretation`)

**Comment by BaptisteAlgoet** [comment]
Aaaaaah.....!
OK, ça fonctionne, maintenant.

Question complémentaire : est-ce qu'on peut utiliser des retours à la ligne ? Et si oui, comment ?

**Comment by joelclems** [comment]
on peut mettre de l'html dans le commentaire
un `<br>` permet d'aller à la ligne. (voir sur la page)
Il faut que les commentaires soient sur une ligne sinon ça ne marche pas

**Comment by BaptisteAlgoet** [comment]
OK. Impeccable. Ça fonctionne.

**Comment by joelclems** [comment]
Il reste à 
- compléter le texte la page résultat
- traiter le cas méjean coeur (attribuer plusieurs ug à un circuit ??)
- voir tableau nb circuits j'ai mis min et max pour le nombre de circuit qui peut fluctuer selon les séries

**Comment by BaptisteAlgoet** [comment]
Je commence à compléter les textes.
Cela dit, comme évoqué hier, en effet, la type n'est pas terrible. Il faudrait _a minima_ augmenter la taille de la police, et éventuellement la passer en noir.
