### ISSUE TITLE
IN & restitution - Réorganisation des menus

### ISSUE THREAD

**Issue by BaptisteAlgoet** [PnCevennes/app_oeasc#27]
Dans la barre de menu, en haut : 

- Prévoir un menu "Résultats des suivis", qui contiendra toutes les pages de restitution "grand public". Pour le moment, y prévoir un sous-menu par volet de l'Observatoire : système d'alerte, diagnostics sylvicoles, ICE (sous-menu avec 3 pages : abondance [= IN] ; performance [= MC / LD] ; pressions sur la végétation [= IC/IA] ), dégâts agricoles, données cynégétiques, suivi des peuplements sensibles. On y ajoutera + tard des entrées géographiques (1 page / secteur).

- Garder un menu "Indice nocturne" pour les admin, avec les pages "saisie" et "données (validation & visualisation)"

**Comment by joelclems** [comment]
J'ai fait un menu
- admin : pour les pages d'administration (utilisateurs, indices nocturne (tableau et saisie)
- dev : pour les développements en cours
- ajout des pages résultats, à remplir...
