### ISSUE TITLE
Ajout mention financeurs

### ISSUE THREAD

**Issue by BaptisteAlgoet** [PnCevennes/app_oeasc#32]
Quelque chose d'important à faire, qu'on aurait du faire depuis un moment, déjà : comme notre projet est financé, on doit ajouter sur la page d'accueil du site, sans que l'utilisateur ne doivent faire défiler la page, les logos des financeurs + une mention à l'Union européenne. Je te mets ça ci-dessous au format image (capture d'écran d'un fichier Word)  : 

![image](https://user-images.githubusercontent.com/68336175/100219232-04212880-2f16-11eb-9a4c-80e6a9173038.png)

Un petit défi de mise en page pour toi, donc...

PS : je te mets ci-dessous aussi une capture d'écran des "obligations de publicité" des financeurs : 
![image](https://user-images.githubusercontent.com/68336175/100219394-3c286b80-2f16-11eb-9f92-74f155252b68.png)

On en reparle si besoin.

**Comment by joelclems** [comment]
Une solution simple serait de faire une image propre avec les 3 logos et de l'ajouter dans le haut du contenu de la page d'accueil.
Ca fait un bon exercice pour tester la fonctionalité inséré/uploader une image dans un contenu.

**Comment by BaptisteAlgoet** [comment]
Bon, j'ai vu que tu l'avais fait, donc merci !
Il faudra que je fasse le test sur une autre page, du coup.
Par contre, tant qu'on y est, si c'est possible, tu pourrais réduire un petit peu la taille du bandeau... Là, c'est un peu trop grand...

**Comment by joelclems** [comment]
J'ai rajouté la hauteur

```
<content-img center
height="120px"
  src="financeurs.png"
  title=""
  source=""></content-img>
```

**Comment by BaptisteAlgoet** [comment]
Excellent. Avec ça je maitrise tout ! Impeccable.

**Comment by BaptisteAlgoet** [comment]
Bug dans l'affichage de l'image, suite à la dernière actualisation de la page...

![image](https://user-images.githubusercontent.com/68336175/101781360-febc0480-3af7-11eb-8091-b95be506b0d1.png)

**Comment by joelclems** [comment]
J'ai remis l'image

**Comment by BaptisteAlgoet** [comment]
L'image est repartie...(!)

![image](https://user-images.githubusercontent.com/68336175/102088930-ddbb2280-3e1b-11eb-8074-7c7c35d5eda3.png)

C'est normal, ça ? Comment ça se fait que ça "saute" comme ça ??

**Comment by joelclems** [comment]
réglé avec la migration
