### ISSUE TITLE
IN : page grand public

### ISSUE THREAD

**Issue by BaptisteAlgoet** [PnCevennes/app_oeasc#33]
Quelques commentaires pour améliorer l'affichage de la page "grand public" de restitution des résultats : 
- [x] mieux séparer les graphiques des différents secteurs : au-dessus du titre du graphique, insérer en grand et/ou gras le nom "officiel" du secteur (Aigoual, Causses-gorges, Mont Lozère, Vallées cévenoles) et ajouter un séparateur (trait horizontal) sous le texte de commentaire (je l'ai pour le moment fait en utilisant les balises < br > et < hr >... dis-moi si on fait comme ça où si tu l'intègres plutôt toi-même)
- [x] mettre les 2 graphiques "Méjean" et "Méjean_coeur" ensemble, dans le même secteur (Causses-gorges)
- [x] réduire un peu la police du titre des graphiques
- [ ] supprimer la légende des graphiques (sous l'axe des abscisses), car elle ne sert à rien puisque l'on affiche une seule série par graphique.

**Comment by joelclems** [comment]
Il faudrait  peut être simplifier cette page en ne présentant que les résultats sur les cerfs (avec peut être une page annexe avec tous les résultats interactif??)
on peut voir aussi une plus grande souplesse sur les graphes aussi

**Comment by joelclems** [comment]
Je propose
https://oeasc.cevennes-parcnational.net/front/#/content/resultats.in_test

**Comment by BaptisteAlgoet** [comment]
J'avoue que je préférais comme c'était fait avant : choix de l'espèce en  interactif, et listing des secteurs en-dessous (avec nom des secteurs en "titre de paragraphe").
Pour moi, avec des séparateurs marqués entre les secteurs, ça reste bien lisible.

Par contre, je ne comprends pas ce que tu veux dire par "on peut voir aussi une plus grande souplesse sur les graphes aussi"...?

Et une nouvelle chose : 
- [ ] Il faut faire apparaître la droite de régression linéaire quand l'évolution est significative (là, on ne la voit plus... est-ce à cause du fiat que tu as mis "méjean" et "méjean_coeur" sur le même graphe ? Si oui, il y a toujours la possibilité de les mettre l'un en dessous de l'autre, mais dans la même partie (secteur Causse - gorges).

**Comment by BaptisteAlgoet** [comment]
J'ai vu que tu avais modifié, mais que tu étais revenue en arrière (choix interactif du secteur et de l'espèce).

Pour rappel, le mieux serait de revenir à comme c'était il y a 15 jours : laisser le choix (interactif) pour l'espèce, mais mettre tous les secteurs sur la page (avec un séparateur net, et en mettant les 2 graphes Méjean & Méjean_coeur dans la même partie).

**Comment by BaptisteAlgoet** [comment]
Décision : Espèce au choix (cerf par défaut) ; texte commun (1 par secteur) qui ne change pas.

**Comment by joelclems** [comment]
- tous les secteurs avec espece au choix
https://oeasc.cevennes-parcnational.net/front/#/content/resultats.in_test

**Comment by BaptisteAlgoet** [comment]
C'est nickel comme ça.
J'ai retouché les textes.

Tu peux copier / coller le contenu de cette page dans la page "grand public".
Je ferai une actualité juste après.

Je prévois aussi un point d'information avec Max.

De mon côté, me reste juste à regarder cette histoire de validité des données, pour chaque circuit et chaque année. Mais ça, ça ne dépend plus de toi, puisque tout fonctionne nickel (a priori).

🥇
