### ISSUE TITLE
Volet "menu"

### ISSUE THREAD

**Issue by BaptisteAlgoet** [PnCevennes/app_oeasc#38]
Petite amélioration à apporter : réduire la largeur du volet "menu", qui s'ouvre sur la gauche.

![image](https://user-images.githubusercontent.com/68336175/102088239-f0812780-3e1a-11eb-9e8f-1695670ef720.png)

Et petit bonus : il n'est apparemment pas facile pour les utilisateurs de trouver les onglet "documentation" ou "contact"...
Ce serait pas mal de trouver une solution pour rendre ce volet plus visible, donc.
Ou alors, il faudrait remettre les pages "documentation", "contact" et "partenaires" en bas de page (ou ailleurs, mais à un emplacement + visible), pour qu'ils puissent être trouvés + facilement.

**Comment by joelclems** [comment]
- On peut pas faire grand chose pour le permier point. La largeur tien compte du titre des sous menus (qui apparraissent au milieu) et de leurs icones s'il y en a et (qui apparaissent à droite)
- Je propose un volet information qui contient ses trois rubrique et qui apparait dans les 2 menus (haut et gauche)

**Comment by BaptisteAlgoet** [comment]
OK. Pas de souci.
C'est pas trop mal comme ça.
Juste une toute petite chose, à la marge : 
- [ ] Remplacer "Informations" par "En savoir plus..."
